#!/usr/bin/env bash
set -euo pipefail

print_recovery_hint() {
  echo "" >&2
  echo "Interrupt detected. RDS Postgres creation usually takes ~5-10 minutes." >&2
  echo "Recovery: wait a minute, then rerun ./scripts/infra-up.sh (terraform is idempotent)." >&2
  echo "To remove everything: ./scripts/infra-down.sh" >&2
}
trap 'print_recovery_hint' INT

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INFRA_DIR="$ROOT_DIR/infra"

"$ROOT_DIR/scripts/bootstrap-deps.sh" terraform aws

MY_IP="$(curl -fsSL https://checkip.amazonaws.com || true)"
if [[ -n "$MY_IP" ]]; then
  ALLOWED_CIDR="${MY_IP}/32"
else
  ALLOWED_CIDR="0.0.0.0/0"
fi
echo "Locking DB access to allowed_cidr=$ALLOWED_CIDR"

printf '\n==> Provisioning RDS Postgres (VPC + subnets + IGW + SG + db). Usually ~5-10 min.\n\n'

cd "$INFRA_DIR"
terraform init -input=false
terraform apply -auto-approve -input=false -var "allowed_cidr=$ALLOWED_CIDR"

DATABASE_URL="$(terraform output -raw database_url)"
DB_HOST="$(terraform output -raw db_endpoint)"
DB_PORT="$(terraform output -raw db_port)"
DB_NAME="$(terraform output -raw db_name)"
DB_USER="$(terraform output -raw db_username)"

cat > "$ROOT_DIR/.env.rds" <<EOF
# Generated by scripts/infra-up.sh — gitignored, do not commit.
DATABASE_URL=$DATABASE_URL
PGHOST=$DB_HOST
PGPORT=$DB_PORT
PGDATABASE=$DB_NAME
PGUSER=$DB_USER
EOF

printf '\nWrote %s (DATABASE_URL + PG* vars).\n' "$ROOT_DIR/.env.rds"
cat <<'NEXT'

Next steps:
  source .env.rds            # load DATABASE_URL + PG* into your shell
  (in ../wt-backend) DATABASE_URL="$DATABASE_URL" npx prisma db push   # create schema on RDS
  re-seed, then start the backend with DATABASE_URL pointing at RDS.

Tear down (stops billing):  ./scripts/infra-down.sh
NEXT
